### PR TITLE
Support JupyterLab console

### PR DESCRIPTION
**Pull request by trungleduc**
## Code changes
- Register widget manager with console widget

### CODE REVIEW

**Comment by trungleduc** [comment]
@davidbrochart could you take a look at this PR?

**Review by davidbrochart — APPROVED** [review]
This looks good to me, thanks @trungleduc.

**Comment by trungleduc** [comment]
Nice, it would be great if you can release a new version with is patch

**Comment by davidbrochart** [comment]
I released v0.3.5.

**Comment by trungleduc** [comment]
Thanks!

**Pull request merged**
